services:
  container:
    image: mailing/mailing:latest
    container_name: mailing-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7373:7373"